### ISSUE TITLE
ImportError: cannot import name RemovedInDjango19Warning错误

### ISSUE THREAD

**Issue by ghost** [zwq1216/CSTplatform#1]
你好，我是一个django开发初学者，在ubuntu18,04上git你的项目作为练习，我的python版本是2.7.14, 其他的环境按照你的项目中requrements.txt进行配置，但我在终端运行项目时，不管运行什么命令，都会提示
`ImportError: cannot import name RemovedInDjango19Warning`错误，网上搜索原因，在djano1.10.x下运行django1.9.x项目会出现这种问题，但我的环境完全按照requrements.txt配置，这是错误的完整部分
```
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/home/dylan/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 10, in <module>
    from django.apps import apps
  File "/home/dylan/.local/lib/python2.7/site-packages/django/apps/__init__.py", line 1, in <module>
    from .config import AppConfig
  File "/home/dylan/.local/lib/python2.7/site-packages/django/apps/config.py", line 6, in <module>
    from django.utils.module_loading import module_has_submodule
  File "/home/dylan/.local/lib/python2.7/site-packages/django/utils/module_loading.py", line 4, in <module>
    from importlib import import_module
  File "/home/dylan/.local/lib/python2.7/site-packages/django/utils/importlib.py", line 6, in <module>
    from django.utils.deprecation import RemovedInDjango19Warning
ImportError: cannot import name RemovedInDjango19Warning
```

**Comment by zwq1216** [comment]
您好，没能重现你的错误。请确保你的配置和requrements.txt配置里面的配置一样，使用python2.7和Django1.9.8
具体配置这个项目如下：
1、进入mysql环境创建”cstplatform”数据库，进入该数据库，将CSTplatform/cc.sql导入该数据库
2、使用pip install -r requrements.txt安装包，如有问题请自行百度查询安装相关包
3、拉下该项目代码（https://github.com/zwq1216/CSTplatform.git)
4、若在本地运行请注意修改setting.py文件中的配置（静态文件和ALLOWED_HOSTS字段）
已成功运行该项目

**Comment by ghost** [comment]
你好,错误原因已经找到,使用的Django版本错误.谢谢回复
